name: Claude Assistant
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - uses: Akira-Papa/claude-code-action@beta  # Fork with OAuth support
        with:
          # Option 1: Direct API (default)
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Option 2: OAuth authentication for Claude Max subscribers
          # use_oauth: "true"
          # claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          # claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          # claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: add custom trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          # Optional: add assignee trigger for issues
          # assignee_trigger: "claude"
          direct_prompt: |
            Update the API documentation in README.md to reflect
            the changes made to the API endpoints in this PR.